# examples:
#   periodic_cleanup:
#     class: CleanSoftDeletedRecordsJob
#     queue: background
#     args: [ 1000, { batch_size: 500 } ]
#     schedule: every hour
#   periodic_cleanup_with_command:
#     command: "SoftDeletedRecord.due.delete_all"
#     priority: 2
#     schedule: at 5am every day

production:
  clear_solid_queue_finished_jobs:
    command: "SolidQueue::Job.clear_finished_in_batches(finished_before: 16.days.ago, sleep_between_batches: 0.3)"
    schedule: every day at 4:15am

  send_day_of_reminder:
    class: SendDayOfReminderJob
    schedule: every hour at minute 5

  send_havent_ordered_reminder:
    class: SendHaventOrderedReminderJob
    schedule: every hour at minute 15

  trim_analytics:
    class: TrimAnalyticsJob
    schedule: every day at 4:30am

  analyze_anomalies:
    class: AnalyzeAnomaliesJob
    schedule: every day at 9:21pm America/New_York

  capture_dyno_metrics:
    class: CaptureDynoMetricsJob
    schedule: "3,33 * * * *"

  capture_db_backup:
    class: CaptureDbBackupJob
    schedule: every Sunday at 3:07am America/New_York
